spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/auth-db"
    username: admin
    password: admin

secret-key: secret

server:
  port: 8080

covid-service:
  base-url: http://localhost:8081
  path: /api/v1/institution